name: Cling Build and Test

on:
  push:
    paths:
      - '**'
  workflow_dispatch:
  release:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
        config:
          - {arch: x86_64, branch: latest-stable}
          - {arch: x86, branch: latest-stable}
          - {arch: aarch64, branch: latest-stable}
          - {arch: armhf, branch: latest-stable}
          - {arch: armv7, branch: latest-stable}
          - {arch: ppc64le, branch: latest-stable}
          - {arch: riscv64, branch: edge}
          - {arch: s390x, branch: latest-stable}
    steps:
      - name: Setup Alpine Linux
        uses: jirutka/setup-alpine@v1
        with:
          arch: ${{ matrix.config.arch }}
          branch: ${{ matrix.config.branch }}
        
      - name: Install deps
        shell: alpine.sh --root {0}
        run: |
          apk update && apk add cmake gcc g++ make libedit python3
        
      - name: Checkout LLVM
        uses: actions/checkout@v4
        with:
          repository: root-project/llvm-project
          path: llvm
          ref: cling-latest
          fetch-depth: 1

      - name: Checkout Cling
        uses: actions/checkout@v4
        with:
          repository: root-project/cling
          path: cling
          fetch-depth: 1

      - name: Prepare build directory
        run: |
          mkdir build

      - name: Configure
        shell: alpine.sh {0}
        working-directory: build
        run: cmake -DLLVM_EXTERNAL_PROJECTS=cling -DLLVM_EXTERNAL_CLING_SOURCE_DIR=../cling/ -DLLVM_ENABLE_PROJECTS="clang" -DLLVM_TARGETS_TO_BUILD="host;NVPTX" -DCMAKE_BUILD_TYPE=Release ../llvm/llvm/

      - name: Build
        shell: alpine.sh {0}
        working-directory: build
        run: cmake --build . --parallel 4 --target cling

      #- name: Test
        #working-directory: build
        #run: cmake --build . --target check-cling

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
    # Artifact name
          name: cling-${{ matrix.config.arch }}
    # A file, directory or wildcard pattern that describes what to upload
          path: build
    # The desired behavior if no files are found using the provided path.
